# print(dir(list))
"""insert"""
a=[25,65,32]
a.insert(2,5)
print(a)
x=[12,65,'hi','hello',4]
print(x)
x.insert(3,'python')
x.insert(2,369)
print(x)
"""pop"""
x=[12,65,'hi','hello',4]
x.pop()
x.pop(2)
print(x)
x=[12,65,'hi','hello',4]
x.pop(0)
x.pop(3)
print(x)
"""remove"""
x=[12,65,'hi','hello',4]
x.remove(12)
x.remove('hi')
print(x)
"""reverse"""
x=[12,65,'hi','hello',4]
x.reverse()
print(x)
"""sort"""
x=[12,65,52,4]
x.sort()
x.sort(reverse=True)
print(x)
x=['a','b','zijuhguij','hd','uhui']
x.sort()
x.sort(reverse=True)
print(x)